# Generated by Django 5.2.1 on 2025-05-13 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
            ],
            options={
                'db_table': 'coords',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('otc', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('other_titles', models.CharField(max_length=20)),
                ('connect', models.CharField(blank=True, null=True)),
                ('add_time', models.DateTimeField()),
                ('winter', models.CharField(blank=True, null=True)),
                ('summer', models.CharField(blank=True, null=True)),
                ('autumn', models.CharField(blank=True, null=True)),
                ('spring', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PEN', 'Pending'), ('ACT', 'Accepted'), ('RJT', 'Rejected')], default='NEW', max_length=3)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='api.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='api.user')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('data', models.CharField()),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.perevaladded')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalareas')),
            ],
            options={
                'db_table': 'pereval_areas',
            },
        ),
    ]
